
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: bogeyboxgolfclub_development
  username: 'angel'
  password: 'fr33l@nC3'
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: bogeyboxgolfclub_test

production:
  <<: *default
  database: bogeyboxgolfclub_production
  username: bogeyboxgolfclub
  password: <%= ENV['BOGEYBOXGOLFCLUB_DATABASE_PASSWORD'] %>
